### ISSUE TITLE
Le spawn est-il normal ?

### ISSUE THREAD

**Issue by Baptiste27140** [Korioz/CaliforniaRP#1]
Bonjour,

Nous avons installé la base, qui est très bien mais on ne comprend pas pourquoi à notre reconnexion, nous ne récupérons pas notre ancienne position.

On spawn de nouveau à la gare, et nous avons le message suivant : Votre personnage n'a pas été créé correctement. Alors faîtes /register.

Cordialement

**Comment by Korioz** [comment]
Problème déjà réglé ici 🙂
https://discord.gg/aFGtaJ4
