### ISSUE TITLE
Banned after joining

### ISSUE THREAD

**Issue by moriokii** [Korioz/CaliforniaRP#6]
Joining to server, awaiting script and i banned from anticheat :/
![image](https://user-images.githubusercontent.com/60312254/140513874-6343f06a-2bef-42c3-8c2c-86cf7ddcb9b2.png)
![image](https://user-images.githubusercontent.com/60312254/140513903-4dd6da26-cf7b-4a9f-850e-1c5a5e3a9c50.png)

**Comment by moriokii** [comment]
And can i disable anti cheat, and rework server for own purposes?

**Comment by Florian-1801** [comment]
Hi, did you by any chance try to remove line 42 from your CFG server containing 'sets credit "Base developed by Korioz"'?
